#!/usr/bin/env python3
"""Wraps the pre-existing infographic PNG in a 16:9 scene the camera can move.

⚠️ THE PNG IS THE INPUT, NOT A BY-PRODUCT. This example simulates a reader who
already owns a raster image and wants an annotated video of it, so nothing here
knows how `resource/image/atmosphere.png` was drawn. Swap the file (PNG or
JPEG) and re-run.

    python3 resource/temp/make_frame_svg.py

⚠️ THE IMAGE IS EMBEDDED AS base64, NOT LINKED. A relative `href` renders in
`animation.html` but breaks at capture, which renders a copy of the page from
`resource/temp/.capture/` where `../image/` no longer resolves.

⚠️ THERE IS NO CAMERA RIG. The `<image>` element is the actor: it takes the move
and the scale itself, and the document's `pivot: top_left` holds the picture's
own origin still under the zoom. Drawn at (0, 0), a picture point p lands on
screen at  pan + zoom × p. Wrapper groups were measured to add nothing.
"""
import base64, pathlib, re, struct

HERE = pathlib.Path(__file__).resolve().parent.parent.parent      # the example root
IMAGE = HERE / "resource/image/atmosphere.png"
OUT = HERE / "resource/scene/atmosphere_frame.svg"
FRAME_W, FRAME_H = 1920, 1080

# ── the dark theme is the source of every fallback ───────────────────────────
THEME = dict(re.findall(r'^\s*(--[a-z-]+):\s*(.+?);',
                        (HERE / "resource/style/theme_dark.css").read_text(), re.M))

def v(name):
    """A var() call carrying the theme's own value as its fallback."""
    assert name in THEME, f"{name} is not declared in theme_dark.css"
    return f"var({name}, {THEME[name]})"

def image_size(data):
    """Pixel size from the file header, so no imaging library is needed."""
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return struct.unpack(">II", data[16:24]), "image/png"
    if data[:2] == b"\xff\xd8":
        i = 2
        while i < len(data):
            marker, length = data[i + 1], struct.unpack(">H", data[i + 2:i + 4])[0]
            if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
                h, w = struct.unpack(">HH", data[i + 5:i + 9])
                return (w, h), "image/jpeg"
            i += 2 + length
    raise SystemExit(f"{IMAGE} is neither a PNG nor a JPEG")

data = IMAGE.read_bytes()
(w, h), mime = image_size(data)
OUT.write_text(f'''<svg id="atmosphere_frame" width="{FRAME_W}" height="{FRAME_H}" viewBox="0 0 {FRAME_W} {FRAME_H}" xmlns="http://www.w3.org/2000/svg">
  <!-- GENERATED by resource/temp/make_frame_svg.py from {IMAGE.relative_to(HERE)} — do not edit. -->
  <rect width="{FRAME_W}" height="{FRAME_H}" fill="{v("--scene-background-color")}"/>
  <image id="atmosphere_infographic" x="0" y="0" width="{w}" height="{h}" href="data:{mime};base64,{base64.b64encode(data).decode()}"/>
</svg>
''')
print(f"{OUT.relative_to(HERE)}  ← {IMAGE.relative_to(HERE)} {w}x{h}")
